# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbRechargeWithdrawHistory',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('inst_no', models.CharField(default=b'81170000', max_length=30)),
                ('client_no', models.CharField(default=b'', max_length=20)),
                ('client_name', models.CharField(max_length=30)),
                ('bank_account', models.CharField(max_length=30)),
                ('inst_func_acc', models.CharField(max_length=30)),
                ('trans_code', models.CharField(max_length=30)),
                ('trans_name', models.CharField(max_length=30)),
                ('occur_balance', models.DecimalField(max_digits=30, decimal_places=5)),
                ('trade_date', models.DateField(null=True, blank=True)),
                ('trade_time', models.TimeField(null=True, blank=True)),
                ('status', models.SmallIntegerField(choices=[(1, '\u6210\u529f'), (2, '\u5931\u8d25')])),
                ('inst_serial', models.CharField(default=b'', max_length=60, db_index=True, blank=True)),
                ('serial_no', models.CharField(default=b'', max_length=60, db_index=True, blank=True)),
                ('entrust_way', models.CharField(default=b'', max_length=6)),
                ('busi_type', models.CharField(default=b'6', max_length=6, choices=[(b'6', '\u4fdd\u8bc1\u91d1'), (b'7', '\u8d37\u6b3e')])),
                ('money_kind', models.CharField(default=b'01', max_length=6)),
                ('err_msg', models.CharField(default=b'', max_length=120, blank=True)),
                ('comment', models.CharField(default=b'', max_length=200, blank=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AbRechargeWithdrawLog',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('entrust_way', models.CharField(default=b'', max_length=6)),
                ('trade_source', models.CharField(max_length=6, choices=[(b'B', '\u94f6\u884c'), (b'I', '\u5e02\u573a')])),
                ('inst_serial', models.CharField(default=b'', max_length=60, db_index=True, blank=True)),
                ('serial_no', models.CharField(default=b'', max_length=60, db_index=True, blank=True)),
                ('inst_no', models.CharField(default=b'81170000', max_length=30)),
                ('busi_type', models.CharField(default=b'6', max_length=6, choices=[(b'6', '\u4fdd\u8bc1\u91d1'), (b'7', '\u8d37\u6b3e')])),
                ('money_kind', models.CharField(default=b'01', max_length=6)),
                ('client_no', models.CharField(default=b'', max_length=20)),
                ('bank_account', models.CharField(default=b'', max_length=30)),
                ('inst_func_acc', models.CharField(max_length=30)),
                ('settle_acc', models.CharField(default=b'', max_length=30)),
                ('transfer_amount', models.PositiveIntegerField()),
                ('client_name', models.CharField(max_length=30)),
                ('trade_branch', models.CharField(default=b'', max_length=200, blank=True)),
                ('event', models.SmallIntegerField(choices=[(1, '\u51fa\u91d1'), (2, '\u5165\u91d1')])),
                ('status', models.SmallIntegerField(choices=[(1, '\u6210\u529f'), (2, '\u5931\u8d25')])),
                ('code', models.CharField(default=b'', max_length=10)),
                ('info', models.CharField(default=b'', max_length=200, blank=True)),
                ('comment', models.CharField(default=b'', max_length=200, blank=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AbRescindContractLog',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('entrust_way', models.CharField(default=b'', max_length=6)),
                ('trade_source', models.CharField(max_length=6, choices=[(b'B', '\u94f6\u884c'), (b'I', '\u5e02\u573a')])),
                ('inst_serial', models.CharField(default=b'', max_length=60, db_index=True, blank=True)),
                ('serial_no', models.CharField(default=b'', max_length=60, db_index=True, blank=True)),
                ('inst_no', models.CharField(default=b'81170000', max_length=30)),
                ('busi_type', models.CharField(default=b'6', max_length=6, choices=[(b'6', '\u4fdd\u8bc1\u91d1'), (b'7', '\u8d37\u6b3e')])),
                ('money_kind', models.CharField(default=b'01', max_length=6)),
                ('client_no', models.CharField(default=b'', max_length=20)),
                ('bank_account', models.CharField(max_length=30)),
                ('inst_func_acc', models.CharField(max_length=30)),
                ('client_name', models.CharField(max_length=30)),
                ('cert_type', models.CharField(default=b'110001', max_length=10)),
                ('cert_id', models.CharField(max_length=30)),
                ('inst_branch', models.CharField(default=b'', max_length=30, blank=True)),
                ('trade_branch', models.CharField(default=b'', max_length=200, blank=True)),
                ('status', models.SmallIntegerField(choices=[(1, '\u6210\u529f'), (2, '\u5931\u8d25')])),
                ('summary', models.CharField(default=b'', max_length=200, blank=True)),
                ('code', models.CharField(default=b'', max_length=10)),
                ('info', models.CharField(default=b'', max_length=200, blank=True)),
                ('comment', models.CharField(default=b'', max_length=200, blank=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AbSignInContractLog',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('status', models.SmallIntegerField(default=3, choices=[(1, '\u6210\u529f'), (2, '\u5931\u8d25'), (3, '\u672a\u63d0\u4ea4'), (4, '\u5904\u7406\u4e2d')])),
                ('code', models.CharField(default=b'', max_length=10)),
                ('info', models.CharField(default=b'', max_length=200, blank=True)),
                ('entrust_way', models.CharField(default=b'I', max_length=6)),
                ('trade_source', models.CharField(default=b'I', max_length=6, choices=[(b'B', '\u94f6\u884c'), (b'I', '\u5e02\u573a')])),
                ('inst_serial', models.CharField(default=b'', max_length=60, db_index=True, blank=True)),
                ('serial_no', models.CharField(default=b'', max_length=60, db_index=True, blank=True)),
                ('inst_no', models.CharField(default=b'81170000', max_length=30)),
                ('busi_type', models.CharField(default=b'6', max_length=6, choices=[(b'6', '\u4fdd\u8bc1\u91d1'), (b'7', '\u8d37\u6b3e')])),
                ('money_kind', models.CharField(default=b'01', max_length=6)),
                ('client_no', models.CharField(default=b'', max_length=20, null=True, blank=True)),
                ('bank_account', models.CharField(max_length=30)),
                ('inst_func_acc', models.CharField(max_length=30)),
                ('client_name', models.CharField(max_length=30)),
                ('cert_type', models.CharField(default=b'110001', max_length=10)),
                ('cert_id', models.CharField(max_length=30)),
                ('inst_branch', models.CharField(default=b'1', max_length=30, blank=True)),
                ('trade_branch', models.CharField(default=b'', max_length=200, blank=True)),
                ('tel_no', models.CharField(default=b'1', max_length=30, null=True, blank=True)),
                ('trade_date', models.DateField(verbose_name='\u4ea4\u6613\u65e5\u671f', null=True, editable=False, blank=True)),
                ('trade_time', models.TimeField(verbose_name='\u4ea4\u6613\u65f6\u95f4', null=True, editable=False, blank=True)),
                ('summary', models.CharField(default=b'', max_length=200, blank=True)),
                ('user_comment', models.CharField(default=b'', max_length=200, blank=True)),
                ('sys_comment', models.CharField(default=b'', max_length=200, blank=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgriculturalBankEncKey',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('package', models.CharField(max_length=128, verbose_name='\u5305\u5bc6\u94a5')),
                ('mac', models.CharField(max_length=128, verbose_name='mac\u5bc6\u94a5')),
                ('pin', models.CharField(max_length=128, verbose_name='\u5173\u952e\u57df\u5bc6\u94a5')),
                ('expire_time', models.DateTimeField(verbose_name='\u8fc7\u671f\u65f6\u95f4', editable=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='AgriculturalBankOriginalKey',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('package', models.CharField(max_length=128, verbose_name='\u5305\u5bc6\u94a5')),
                ('mac', models.CharField(max_length=128, verbose_name='mac\u5bc6\u94a5')),
                ('pin', models.CharField(max_length=128, verbose_name='\u5173\u952e\u57df\u5bc6\u94a5')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
    ]
