# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0008_auto_20150924_1125'),
        ('address', '0003_receivingaddress'),
        ('commission', '0002_auto_20151016_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupAddr',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=15, verbose_name='\u540d\u5b57')),
                ('addr', models.CharField(max_length=200, verbose_name='\u5730\u5740')),
                ('tel', models.CharField(max_length=30, verbose_name='\u7535\u8bdd')),
                ('contact', models.CharField(max_length=30, verbose_name='\u8054\u7cfb\u4eba')),
                ('lat', models.FloatField(max_length=15, verbose_name='\u7eac\u5ea6')),
                ('lng', models.FloatField(max_length=15, verbose_name='\u7ecf\u5ea6')),
                ('desc', models.CharField(max_length=1000, verbose_name='\u5907\u6ce8')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('city', models.ForeignKey(related_name='pickup_addr_city', verbose_name='\u57ce\u5e02', to='address.City')),
                ('province', models.ForeignKey(related_name='pickup_addr_province', verbose_name='\u7701', to='address.Province')),
            ],
        ),
        migrations.CreateModel(
            name='StockProductConfig',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quote', models.IntegerField(null=True, verbose_name='\u8fdb\u8d27\u6743', blank=True)),
                ('opening_price', models.FloatField(null=True, verbose_name='\u4e0a\u5e02\u4ef7\u683c', blank=True)),
                ('opening_date', models.DateField(null=True, verbose_name='\u4e0a\u5e02\u65f6\u95f4', blank=True)),
                ('trade_unit', models.CharField(max_length=15, verbose_name='\u4ea4\u6613\u5355\u4f4d')),
                ('hold_users_limit', models.IntegerField(null=True, verbose_name='\u6301\u6709\u4eba\u6570\u4e0a\u9650', blank=True)),
                ('min_pickup_num', models.IntegerField(null=True, verbose_name='\u6700\u5c0f\u63d0\u8d27\u91cf', blank=True)),
                ('min_price', models.FloatField(null=True, verbose_name='\u6700\u5c0f\u53d8\u52a8\u4ef7\u4f4d', blank=True)),
                ('min_price_deddigit', models.IntegerField(null=True, verbose_name='\u5c0f\u6570\u4f4d', blank=True)),
                ('min_bnum', models.IntegerField(null=True, verbose_name='\u6700\u5c0f\u4e70\u7533\u62a5\u5355\u4f4d', blank=True)),
                ('min_snum', models.IntegerField(null=True, verbose_name='\u6700\u5c0f\u5356\u7533\u62a5\u5355\u4f4d', blank=True)),
                ('once_max_num', models.IntegerField(null=True, verbose_name='\u5355\u7b14\u6700\u5927\u4e0b\u5355\u91cf', blank=True)),
                ('safefee_rate', models.FloatField(null=True, verbose_name='\u65e5\u4fdd\u9669\u8d39\u6807\u51c6', blank=True)),
                ('st_unit', models.CharField(max_length=15, verbose_name='\u4ed3\u50a8\u8d39\u8ba1\u8d39\u5355\u4f4d')),
                ('strate', models.FloatField(null=True, verbose_name='\u4ed3\u50a8\u8d39\u7387', blank=True)),
                ('pickup_bait', models.FloatField(null=True, verbose_name='\u63d0\u53d6\u4fdd\u969c\u91d1(%)', blank=True)),
                ('pickup_rate', models.FloatField(default=0, null=True, verbose_name='\u63d0\u8d27\u624b\u7eed\u8d39', blank=True)),
                ('pack_rate', models.FloatField(default=0, null=True, verbose_name='\u5305\u88c5\u8d39\u7387', blank=True)),
                ('depositfee_rate', models.FloatField(null=True, verbose_name='\u6258\u7ba1\u8d39', blank=True)),
                ('mark_level', models.IntegerField(null=True, verbose_name='\u884c\u60c5\u6863\u4f4d', blank=True)),
                ('close_price_time', models.IntegerField(null=True, verbose_name='\u6536\u76d8\u4ef7\u8ba1\u7b97\u65f6\u95f4', blank=True)),
                ('max_inc_rate', models.FloatField(null=True, verbose_name='\u6700\u5927\u589e\u6301\u6bd4\u4f8b', blank=True)),
                ('max_dec_rate', models.FloatField(null=True, verbose_name='\u6700\u5927\u51cf\u6301\u6bd4\u4f8b', blank=True)),
                ('commcal_typedata', models.IntegerField(verbose_name='\u4ea4\u6613\u624b\u7eed\u8d39\u7c7b\u578b', choices=[(1, b'\xe5\xae\x9a\xe9\x87\x8f'), (2, b'\xe6\xaf\x94\xe4\xbe\x8b')])),
                ('ud_sty', models.IntegerField(verbose_name='\u6da8\u8dcc\u8ba1\u7b97\u7c7b\u578b', choices=[(1, b'\xe5\xae\x9a\xe9\x87\x8f'), (2, b'\xe6\xaf\x94\xe4\xbe\x8b')])),
                ('ud_up_range', models.FloatField(max_length=15, verbose_name='\u6da8\u5e45\u53c2\u6570')),
                ('ud_down_range', models.FloatField(max_length=15, verbose_name='\u8dcc\u5e45\u53c2\u6570')),
                ('bcomm', models.FloatField(max_length=15, verbose_name='\u4e70\u624b\u7eed\u8d39\u53c2\u6570')),
                ('scomm', models.FloatField(max_length=15, verbose_name='\u5356\u624b\u7eed\u8d39\u53c2\u6570')),
                ('delay_fee_rate', models.FloatField(max_length=15, verbose_name='\u5ef6\u671f\u8865\u507f\u8d39\u7387')),
                ('youhuirage', models.FloatField(max_length=15, verbose_name='\u5f85\u8fd4\u6bd4\u4f8b')),
                ('interest', models.FloatField(max_length=15, verbose_name='\u59d4\u6258\u8d39\u7387')),
                ('ower', models.CharField(max_length=15, verbose_name='\u53d1\u884c\u4ea4\u6613\u5546')),
                ('market_capitalization', models.FloatField(max_length=15, verbose_name='\u5e02\u503c')),
                ('pickup_price', models.FloatField(max_length=15, verbose_name='\u63d0\u8d27\u8d39\u7528')),
                ('checked_user', models.CharField(max_length=15, verbose_name='\u5ba1\u6279\u8005')),
                ('is_checked', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5ba1\u6279')),
                ('is_enable', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e0a\u5e02')),
                ('desc', models.CharField(max_length=1000, verbose_name='\u5907\u6ce8')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', db_index=True)),
                ('created_time', models.TimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_date', models.DateField(auto_now_add=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('modified_time', models.TimeField(auto_now_add=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('product', models.ForeignKey(related_name='stock_config_product', verbose_name='\u5546\u54c1', to='catalogue.Product')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u914d\u7f6e\u8868',
                'verbose_name_plural': '\u5546\u54c1\u914d\u7f6e\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('balance', models.FloatField(max_length=30, null=True, verbose_name='\u4f59\u989d', blank=True)),
                ('locked', models.FloatField(max_length=30, null=True, verbose_name='\u51bb\u7ed3', blank=True)),
                ('desc', models.CharField(max_length=1000, verbose_name='\u5907\u6ce8')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', db_index=True)),
                ('created_time', models.TimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_date', models.DateField(auto_now_add=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('modified_time', models.TimeField(auto_now_add=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('user', models.ForeignKey(related_name='balance_user', verbose_name='\u7528\u6237', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBank',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_name', models.CharField(max_length=15, verbose_name='\u771f\u5b9e\u59d3\u540d')),
                ('id_card_no', models.CharField(max_length=30, verbose_name='\u8eab\u4efd\u8bc1')),
                ('bank_name', models.CharField(max_length=30, verbose_name='\u94f6\u884c\u540d')),
                ('bank_account', models.CharField(max_length=30, verbose_name='\u94f6\u884c\u8d26\u53f7')),
                ('tel', models.CharField(max_length=30, verbose_name='\u7535\u8bdd')),
                ('is_enable', models.BooleanField(default=False, verbose_name='\u662f\u5426\u542f\u7528')),
                ('desc', models.CharField(max_length=1000, verbose_name='\u5907\u6ce8')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('user', models.ForeignKey(related_name='bank_user', verbose_name='\u7528\u6237', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMoneyChange',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('trade_type', models.IntegerField(db_index=True, verbose_name='\u7c7b\u578b', choices=[(1, b'\xe5\x85\x85\xe5\x80\xbc'), (2, b'\xe4\xbd\x93\xe7\x8e\xb0'), (3, b'\xe8\xb4\xad\xe4\xb9\xb0'), (4, b'\xe8\xbf\x9b\xe8\xb4\xa7'), (5, b'\xe5\x87\xba\xe5\x94\xae'), (6, b'\xe6\x8f\x90\xe8\xb4\xa7\xe8\xb4\xb9\xe7\x94\xa8'), (7, b'\xe6\x92\xa4\xe5\x8d\x95')])),
                ('status', models.IntegerField(db_index=True, verbose_name='\u72b6\u6001', choices=[(1, b'\xe6\x88\x90\xe5\x8a\x9f'), (2, b'\xe5\xa4\xb1\xe8\xb4\xa5'), (3, b'\xe5\x86\xbb\xe7\xbb\x93'), (4, b'\xe8\xa7\xa3\xe5\x86\xbb')])),
                ('price', models.FloatField(max_length=15, verbose_name='\u4ef7\u683c')),
                ('commission_buy_no', models.CharField(max_length=15, verbose_name='\u59d4\u6258\u4e70\u7f16\u53f7')),
                ('commission_unit_price', models.FloatField(max_length=15, verbose_name='\u59d4\u6258\u4e70\u4ef7\u683c')),
                ('commission_sale_no', models.CharField(max_length=15, verbose_name='\u59d4\u6258\u5356\u7f16\u53f7')),
                ('trade_no', models.CharField(max_length=15, null=True, verbose_name='\u6210\u4ea4\u7f16\u53f7', blank=True)),
                ('trade_unit_price', models.FloatField(null=True, verbose_name='\u6210\u4ea4\u4ef7\u683c', blank=True)),
                ('trade_quantity', models.FloatField(max_length=15, null=True, verbose_name='\u6210\u4ea4\u6570\u91cf', blank=True)),
                ('pickup_detail_id', models.CharField(max_length=15, null=True, verbose_name='\u63d0\u8d27\u660e\u7ec6ID', blank=True)),
                ('money_bank_id', models.CharField(max_length=15, null=True, verbose_name='\u94f6\u884cID', blank=True)),
                ('money_bank', models.CharField(max_length=15, null=True, verbose_name='\u94f6\u884c', blank=True)),
                ('desc', models.CharField(max_length=1000, verbose_name='\u5907\u6ce8')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', db_index=True)),
                ('created_time', models.TimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_date', models.DateField(auto_now_add=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('modified_time', models.TimeField(auto_now_add=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('product', models.ForeignKey(related_name='money_change_product', verbose_name='\u5546\u54c1', blank=True, to='catalogue.Product')),
                ('user', models.ForeignKey(related_name='money_chanage_user', verbose_name='\u7528\u6237', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPickupAddr',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=15, verbose_name='\u540d\u5b57')),
                ('tel', models.CharField(max_length=30, verbose_name='\u7535\u8bdd')),
                ('id_card_no', models.CharField(max_length=30, verbose_name='\u8eab\u4efd\u8bc1')),
                ('plate_number', models.CharField(max_length=30, verbose_name='\u8f66\u724c\u53f7')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('pickup_addr', models.ForeignKey(related_name='user_pickup_addr', verbose_name='\u81ea\u63d0\u70b9', to='commission.PickupAddr')),
                ('user', models.ForeignKey(related_name='user_pickup_addr_user', verbose_name='\u7528\u6237', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='commissionbuy',
            name='status',
            field=models.IntegerField(db_index=True, verbose_name='\u72b6\u6001', choices=[(1, b'\xe5\xbe\x85\xe6\x88\x90\xe4\xba\xa4'), (2, b'\xe9\x83\xa8\xe5\x88\x86\xe6\x88\x90\xe4\xba\xa4'), (3, b'\xe6\x88\x90\xe4\xba\xa4'), (3, b'\xe6\x92\xa4\xe5\x8d\x95')]),
        ),
        migrations.AlterField(
            model_name='commissionbuy',
            name='unit_price',
            field=models.FloatField(db_index=True, null=True, verbose_name='\u5355\u4ef7', blank=True),
        ),
        migrations.AlterField(
            model_name='commissionbuybackup',
            name='status',
            field=models.IntegerField(db_index=True, verbose_name='\u72b6\u6001', choices=[(1, b'\xe5\xbe\x85\xe6\x88\x90\xe4\xba\xa4'), (2, b'\xe9\x83\xa8\xe5\x88\x86\xe6\x88\x90\xe4\xba\xa4'), (3, b'\xe6\x88\x90\xe4\xba\xa4'), (3, b'\xe6\x92\xa4\xe5\x8d\x95')]),
        ),
        migrations.AlterField(
            model_name='commissionbuybackup',
            name='unit_price',
            field=models.FloatField(db_index=True, null=True, verbose_name='\u5355\u4ef7', blank=True),
        ),
        migrations.AlterField(
            model_name='commissionsale',
            name='status',
            field=models.IntegerField(db_index=True, verbose_name='\u72b6\u6001', choices=[(1, b'\xe5\xbe\x85\xe6\x88\x90\xe4\xba\xa4'), (2, b'\xe9\x83\xa8\xe5\x88\x86\xe6\x88\x90\xe4\xba\xa4'), (3, b'\xe6\x88\x90\xe4\xba\xa4'), (3, b'\xe6\x92\xa4\xe5\x8d\x95')]),
        ),
        migrations.AlterField(
            model_name='commissionsale',
            name='unit_price',
            field=models.FloatField(db_index=True, null=True, verbose_name='\u5355\u4ef7', blank=True),
        ),
        migrations.AlterField(
            model_name='commissionsalebackup',
            name='status',
            field=models.IntegerField(db_index=True, verbose_name='\u72b6\u6001', choices=[(1, b'\xe5\xbe\x85\xe6\x88\x90\xe4\xba\xa4'), (2, b'\xe9\x83\xa8\xe5\x88\x86\xe6\x88\x90\xe4\xba\xa4'), (3, b'\xe6\x88\x90\xe4\xba\xa4'), (3, b'\xe6\x92\xa4\xe5\x8d\x95')]),
        ),
        migrations.AlterField(
            model_name='commissionsalebackup',
            name='unit_price',
            field=models.FloatField(db_index=True, null=True, verbose_name='\u5355\u4ef7', blank=True),
        ),
        migrations.AlterField(
            model_name='stockticker',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', db_index=True),
        ),
        migrations.AlterField(
            model_name='tradecomplete',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', db_index=True),
        ),
    ]
